name: Build BHN NCO Schedule
on:
  push:
    branches: [ main ]        # <- use your default branch
    paths:
      - '_data/ncos.yml'      # input config the script reads
      - 'bhn/scripts/**'      # the script itself
  schedule:
    - cron: '17 11 * * *'     # 11:17 UTC ≈ 07:17 ET (DST)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pyyaml

      # (Optional) See what the runner actually has
      - name: List repo tree
        run: |
          pwd
          ls -R

      - name: Generate schedule
        run: python bhn/scripts/build_bhn_data.py

      - name: Commit changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/bhn_ncos_schedule.yml
          git diff --staged --quiet || git commit -m "chore: update BHN NCO schedule"
          git diff --staged --quiet || git push
