# .github/workflows/build.yml
name: Generate NCO + Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "_data/**"
      - "scripts/**"        # 👈 if your script is under bhn/scripts/, change to "bhn/scripts/**"
      - "_includes/**"
      - "_layouts/**"
      - "assets/**"
      - "_config.yml"
      - "Gemfile*"
      - "**.md"
      - "**.html"
  schedule:
    - cron: "17 11 * * *"   # daily ~07:17 ET (DST)
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history so we can push)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install pyyaml

      - name: Assert generator exists
        run: |
          set -e
          test -f scripts/build_bhn_data.py || { echo "::error ::missing scripts/build_bhn_data.py"; exit 1; }
          # If your script is actually bhn/scripts/build_bhn_data.py, use this instead:
          # test -f bhn/scripts/build_bhn_data.py || { echo "::error ::missing bhn/scripts/build_bhn_data.py"; exit 1; }

      - name: Run generator
        env:
          STRICT_NCO: "0"  # don't fail build if there are TBD/unassigned rows
        run: |
          python3 scripts/build_bhn_data.py
          # If it's in bhn/scripts/, use:
          # python3 bhn/scripts/build_bhn_data.py

          echo "----- HEAD of generated YAML -----"
          sed -n '1,30p' _data/bhn_ncos_schedule.yml || true
          echo "----- TAIL of generated YAML -----"
          tail -n 30 _data/bhn_ncos_schedule.yml || true

      - name: Commit & push updated schedule
        if: github.ref == 'refs/heads/main'
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/bhn_ncos_schedule.yml
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "chore: update BHN NCO schedule [skip ci]"
            git push
          fi

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.1"
          bundler-cache: true

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
