name: Generate NCO Schedule + Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.html'
      - '_data/**'
      - '_includes/**'
      - '_layouts/**'
      - 'assets/**'
      - '_config.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'scripts/**'
  schedule:
    - cron: '17 11 * * *'   # 11:17 UTC ≈ 07:17 ET during DST
  workflow_dispatch:

permissions:
  contents: write      # needed to commit data changes
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - run: pip install pyyaml

      - name: Generate schedule
        run: bhn/python /bhn/scripts/build_bhn_ncos_schedule.py

      - name: Commit data changes (if any)
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add _data/bhn_ncos_schedule.yml
          git diff --staged --quiet || git commit -m "chore: update BHN NCO schedule"
          git diff --staged --quiet || git push

  build:
    needs: generate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - name: Install deps
        run: bundle install --jobs 4 --retry 3

      - name: Build site
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
