name: Generate NCO + Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - '**.md'
      - '**.html'
      - '_data/**'
      - '_includes/**'
      - '_layouts/**'
      - 'assets/**'
      - '_config.yml'
      - 'Gemfile'
      - 'Gemfile.lock'
      - 'scripts/**'
  schedule:
    - cron: '17 11 * * *'   # 11:17 UTC ≈ 07:17 ET in DST
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # --- Generate the NCO schedule (workspace will carry it into the build) ---
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Python deps
        run: pip install pyyaml
      - name: Run generator
        run: |
          set -euo pipefail
          if [ -f scripts/build_bhn_schedule.py ]; then
            python scripts/build_bhn_schedule.py
          elif [ -f scripts/build_bhn_data.py ]; then
            python scripts/build_bhn_data.py
          else
            echo "ERROR: no generator script found under scripts/"; exit 1
          fi

      - name: Show commit + schedule page content
        run: |
          echo "Commit: $GITHUB_SHA on $GITHUB_REF_NAME"
          git log -1 --pretty=oneline
          echo "----- first 80 lines of nets/blind-hams/bhn-schedule.md -----"
          sed -n '1,80p' nets/blind-hams/bhn-schedule.md || true
          echo "----- any nco_table includes in repo -----"
          grep -RIn "nco_table.html" -- * || true

      - name: Add file snapshot to Summary
        run: |
