# .github/workflows/build.yml
name: Generate NCO + Build & Deploy

on:
  push:
    branches: [ main ]
    paths:
      - "_data/**"
      - "scripts/**"        # 👈 if your script is under bhn/scripts/, change to "bhn/scripts/**"
      - "_includes/**"
      - "_layouts/**"
      - "assets/**"
      - "_config.yml"
      - "Gemfile*"
      - "**.md"
      - "**.html"
  schedule:
    # Daily run at 21:00 UTC as requested
    - cron: "0 21 * * *"
    # Hourly sweep to refresh next_net when occurrences roll over
    - cron: "0 * * * *"
    # Saturday post‑BHN commit after the 10:00–11:00 ET net ends (safe year‑round)
    - cron: "10 17 * * 6"  # Saturdays 17:10 UTC
    # After Patricia's 20:00 ET Saturday net ends (~21:00 ET), push shortly after
    - cron: "10 2 * * 0"   # Sundays 02:10 UTC
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (full history so we can push)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: pip install pyyaml

      - name: Assert generator exists
        run: |
          set -e
          test -f scripts/build_bhn_data.py || { echo "::error ::missing scripts/build_bhn_data.py"; exit 1; }
          test -f scripts/build_next_net.py || { echo "::error ::missing scripts/build_next_net.py"; exit 1; }
          # If your script is actually bhn/scripts/build_bhn_data.py, use this instead:
          # test -f bhn/scripts/build_bhn_data.py || { echo "::error ::missing bhn/scripts/build_bhn_data.py"; exit 1; }

      - name: Run generator
        env:
          STRICT_NCO: "0"  # don't fail build if there are TBD/unassigned rows
        run: |
          python3 scripts/build_bhn_data.py
          python3 scripts/build_next_net.py
          # If it's in bhn/scripts/, use:
          # python3 bhn/scripts/build_bhn_data.py

          echo "----- HEAD of next-net YAML -----"
          sed -n '1,30p' _data/next_net.yml || true
          echo "----- TAIL of next-net YAML -----"
          tail -n 30 _data/next_net.yml || true

          echo "----- HEAD of generated YAML -----"
          sed -n '1,30p' _data/bhn_ncos_schedule.yml || true
          echo "----- TAIL of generated YAML -----"
          tail -n 30 _data/bhn_ncos_schedule.yml || true

      - name: Commit & push updated schedule
        if: github.ref == 'refs/heads/main'
        id: commit
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          # Always stage schedule + next_net; script avoids noisy diffs
          git add _data/bhn_ncos_schedule.yml _data/next_net.yml || true
          if git diff --cached --quiet; then
            echo "No changes to commit."
            echo "changed=false" >> "$GITHUB_OUTPUT"
          else
            git commit -m "chore: refresh schedules [skip ci]"
            git push
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.3"
          bundler-cache: true

      - name: Build site
        if: github.event_name == 'push' || steps.commit.outputs.changed == 'true'
        env:
          JEKYLL_ENV: production
        run: bundle exec jekyll build --trace

      - name: Upload artifact
        if: github.event_name == 'push' || steps.commit.outputs.changed == 'true'
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
        if: github.event_name == 'push' || needs.build.result == 'success'
