# .github/workflows/netlify_build_hook.yml
name: Trigger Netlify (Build Hook)

on:
  push:
    branches: [ main ]
    paths:
      - '_data/next_net.yml'
      - '_data/bhn_ncos_schedule.yml'
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Netlify Build Hook
        env:
          NETLIFY_BUILD_HOOK_URL: ${{ secrets.NETLIFY_BUILD_HOOK_URL }}
        run: |
          if [ -z "$NETLIFY_BUILD_HOOK_URL" ]; then
            echo "::error ::NETLIFY_BUILD_HOOK_URL secret is not set"
            exit 1
          fi
          echo "Calling Netlify build hook (push-only)…"
          curl -sS -X POST -d '{}' "$NETLIFY_BUILD_HOOK_URL"
          echo "Done."
